<?php

namespace NO\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InternauteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InternauteRepository extends EntityRepository
{
	public function getInternautesLesPlusAges($limit = 5){
	
		$qb = $this->createQueryBuilder("j");
		$qb->add('orderBy', 'j.datedenaissance ASC')
		->setMaxResults($limit);

		$query = $qb->getQuery();
		return $query->getResult();
   }
	public function gettAllInternautes($limit = 5){
	
		$qb = $this->createQueryBuilder("j");
		$qb->add('orderBy', 'j.nom ASC');

		$query = $qb->getQuery();
		return $query->getResult();
   }   
}
